household_power_consumption <- read.table("household_power_consumption.txt", sep=";", quote="\"")
household_power_consumption$V1 <- as.Date(as.character(household_power_consumption$V1), "%d/%m/%Y")
data <- subset(household_power_consumption,V1 >= as.Date("2007-02-01") & V1 <= as.Date("2007-02-02"))
data$V3 <- as.numeric(as.character(data$V3))
png('plot1.png',width=480,height=480,units="px",bg = "transparent")
hist(data$V3, main="Global Active Power", xlab="Global Active Power (kilowatts)", col="red")
dev.off()